name: UPDATE_APP_ACTION

on:
  push:
    branches:
      - master
jobs:
  update-readme-with-appinfo:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        env:
          MY_API_KEY: ${{secrets.MY_API_KEY}}  # Reference the secret here
        run: |
          # Use MY_API_KEY in your commands
          echo "this is the code: $MY_API_KEY"
