name: Your Workflow Name

on:
  push:
    branches:
      - main  # Adjust this according to your branch name

jobs:
  your-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      # Add your other steps here

      - name: Use Secret in Workflow
        env:
          MY_API_KEY: ${{ secrets.MY_API_KEY }}  # Reference the secret here
        run: |
          # Use MY_API_KEY in your commands
          echo "Using API key: $MY_API_KEY"
